"""schema inicial

Revision ID: 1d31bb056433
Revises: 
Create Date: 2026-09-20 16:14:46.188396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d31bb056433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cod_municipio', sa.String(length=7), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('op_simples_nacional', sa.String(length=1), nullable=True),
    sa.Column('regime_apuracao_sn', sa.String(length=1), nullable=True),
    sa.Column('regime_especial_trib', sa.String(length=1), nullable=True),
    sa.Column('aliquota_atual', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('tomador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cod_municipio', sa.String(length=7), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='aprovado', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pendente', 'aprovado')", name='ck_tomador_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('certificado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestador_id', sa.UUID(), nullable=False),
    sa.Column('pfx_criptografado', sa.LargeBinary(), nullable=False),
    sa.Column('senha_criptografada', sa.LargeBinary(), nullable=False),
    sa.Column('chave_kms_ref', sa.String(length=200), nullable=True, comment='Identifica qual chave/versão do KMS cifrou este registro. Nulo = chave local de dev.'),
    sa.Column('validade', sa.Date(), nullable=True, comment='Vencimento do certificado A1 — ver Contingências.'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestador_id')
    )
    op.create_table('despesa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestador_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestador_tomador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestador_id', sa.UUID(), nullable=False),
    sa.Column('tomador_id', sa.UUID(), nullable=False),
    sa.Column('apelido', sa.String(length=100), nullable=False, comment='Ex.: "AWIN", "AWIN Rchlo", "Squad Época"'),
    sa.Column('cod_local_prestacao', sa.String(length=7), nullable=False),
    sa.Column('cod_trib_nacional', sa.String(length=6), nullable=False),
    sa.Column('cod_trib_municipal', sa.String(length=5), nullable=True),
    sa.Column('template_descricao', sa.Text(), nullable=False),
    sa.Column('metodo_captura_valor', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('serie', sa.String(length=5), server_default='1', nullable=False),
    sa.Column('requer_revisao', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("metodo_captura_valor IN ('manual', 'pdf', 'csv', 'chat')", name='ck_prestador_tomador_metodo'),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tomador_id'], ['tomador.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestador_id', 'apelido', name='uq_prestador_tomador_apelido')
    )
    op.create_table('emissao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestador_tomador_id', sa.UUID(), nullable=False),
    sa.Column('prestador_id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False, comment='AAAA-MM'),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=False),
    sa.Column('n_dps', sa.Integer(), nullable=True),
    sa.Column('chave_acesso', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='rascunho', nullable=False),
    sa.Column('tomador_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('xml_dps', sa.Text(), nullable=True),
    sa.Column('xml_assinado', sa.Text(), nullable=True),
    sa.Column('xml_resposta', sa.Text(), nullable=True),
    sa.Column('danfse_path', sa.Text(), nullable=True),
    sa.Column('erro_detalhe', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('rascunho','montado','assinado','submetido','confirmado','cancelada','substituida','erro')", name='ck_emissao_estado'),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prestador_tomador_id'], ['prestador_tomador.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso'),
    sa.UniqueConstraint('prestador_id', 'serie', 'n_dps', name='uq_emissao_prestador_serie_ndps')
    )
    op.create_index('uq_emissao_vinculo_competencia_ativa', 'emissao', ['prestador_tomador_id', 'competencia'], unique=True, postgresql_where=sa.text("estado != 'cancelada'"))
    op.create_table('pagamento_recebido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestador_tomador_id', sa.UUID(), nullable=False),
    sa.Column('prestador_id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origem IN ('manual', 'extrato')", name='ck_pagamento_origem'),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prestador_tomador_id'], ['prestador_tomador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('emissao_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("canal IN ('download','email','whatsapp','direto_fornecedor','mensagem_pronta')", name='ck_envio_canal'),
    sa.CheckConstraint("status IN ('pendente','enviado','falha')", name='ck_envio_status'),
    sa.ForeignKeyConstraint(['emissao_id'], ['emissao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envio')
    op.drop_table('pagamento_recebido')
    op.drop_index('uq_emissao_vinculo_competencia_ativa', table_name='emissao', postgresql_where=sa.text("estado != 'cancelada'"))
    op.drop_table('emissao')
    op.drop_table('prestador_tomador')
    op.drop_table('despesa')
    op.drop_table('certificado')
    op.drop_table('tomador')
    op.drop_table('prestador')
    # ### end Alembic commands ###
